module Blog.HelloLivingStyleguide exposing (decodeModel, main, meta, view)

import Data.Meta exposing (Meta)
import Html
import Html.Styled
    exposing
        ( Html
        , a
        , article
        , button
        , div
        , form
        , h3
        , h4
        , input
        , label
        , li
        , main_
        , optgroup
        , option
        , p
        , section
        , select
        , span
        , text
        , textarea
        , toUnstyled
        , ul
        )
import Html.Styled.Attributes exposing (attribute, class, href, name, placeholder, type_, value)
import Json.Decode as Decode exposing (Decoder, Value)
import Route exposing (Route(..), Slug(..))
import Styled
import Tagging exposing (Tag(..))
import Time.Date as Date exposing (Date)


meta : Meta
meta =
    { abstract =
        Just
        """
        This is the living documentation for my own little set of responsive
        Block Element Modifier (BEM) based CSS layout blocks being used throughout
        my blog. Don't expect any content here :-).
        """
    , abstractTagline = Just "Hello Living Styleguide"
    , date = Date.date 2017 1 18
    , route = Article Blog_2017_01_18_hello_living_style_guide
    , tags =
        [ Misc "BEM"
        , Misc "HTML"
        ]
    , title = "Hello Living Styleguide"
    }


decodeModel : Decoder Model
decodeModel =
    Decode.map Model
        (Decode.field "who" Decode.string)


main : Program Never Model ()
main =
    Html.beginnerProgram
        { model =
            { who = "No-One"
            }
        , update = \_ model -> model
        , view = view
        }


type alias Model =
    { who : String
    }


view : Model -> Html.Html ()
view model =
    Styled.layout []
        [ Styled.layoutMain []
            [ Styled.mainHeader []
                [ Styled.intro "Some Grand Intro" "And Subscript"
                , Styled.frontmatter Nothing meta.tags
                , Styled.articleHeader meta.abstractTagline meta.abstract
                ]
            , Styled.mainContent legacyContent
            ]
        , Styled.outro
        ]
        |> toUnstyled


legacyContent : List (Html msg)
legacyContent =
    [ div [ class "ui-grid__row" ]
        [ section [ class "ui-grid__col-8 ui-article-list" ]
            [ h3 []
                [ text "Recent posts" ]
            , ul []
                [ li [ class "ui-article-list__item" ]
                    [ article [ class "ui-article-preview" ]
                        [ h4 [ class "ui-article-preview__title" ]
                            [ a [ href "#" ]
                                [ text "Second post" ]
                            ]
                        , p [ class "ui-article-preview__abstract" ]
                            [ text "The first lines of this post that gives the reader an idea what to expect from this post.                    " ]
                        , ul [ class "ui-article-preview__tags" ]
                            [ li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Some tag" ]
                                    ]
                                ]
                            , li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Another tag" ]
                                    ]
                                ]
                            ]
                        , div [ class "ui-article-preview__date" ]
                            [ text "Wednesday 2017-02-01" ]
                        , a [ class "ui-button", href "#" ]
                            [ span [ class "ui-button__label" ]
                                [ text "Read More...                        " ]
                            ]
                        ]
                    ]
                , li [ class "ui-article-list__item" ]
                    [ article [ class "ui-article-preview" ]
                        [ h4 [ class "ui-article-preview__title" ]
                            [ a [ href "#" ]
                                [ text "First post" ]
                            ]
                        , p [ class "ui-article-preview__abstract" ]
                            [ text "The first lines of this post that gives the reader an idea what to expect from this post.                    " ]
                        , ul [ class "ui-article-preview__tags" ]
                            [ li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Some tag" ]
                                    ]
                                ]
                            , li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Another tag" ]
                                    ]
                                ]
                            ]
                        , div [ class "ui-article-preview__date" ]
                            [ text "Wednesday 2017-02-01" ]
                        , a [ class "ui-button", href "#" ]
                            [ span [ class "ui-button__label" ]
                                [ text "Read More...                        " ]
                            ]
                        ]
                    ]
                , li [ class "ui-article-list__item" ]
                    [ article [ class "ui-article-preview x-ui-article-preview--size-compact" ]
                        [ h4 [ class "ui-article-preview__title" ]
                            [ a [ href "#" ]
                                [ text "An older post with a really long title that just might wrap around" ]
                            ]
                        , p [ class "ui-article-preview__abstract" ]
                            [ text "The first lines of this post that gives the reader an idea what to expect from this post.                    " ]
                        , ul [ class "ui-article-preview__tags" ]
                            [ li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Some tag" ]
                                    ]
                                ]
                            , li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Another tag" ]
                                    ]
                                ]
                            ]
                        , div [ class "ui-article-preview__date" ]
                            [ text "Wednesday 2017-02-01" ]
                        , a [ class "ui-button", href "#" ]
                            [ span [ class "ui-button__label" ]
                                [ text "Read More...                        " ]
                            ]
                        ]
                    ]
                , li [ class "ui-article-list__item" ]
                    [ article [ class "ui-article-preview x-ui-article-preview--size-compact" ]
                        [ h4 [ class "ui-article-preview__title" ]
                            [ a [ href "#" ]
                                [ text "An even older post" ]
                            ]
                        , p [ class "ui-article-preview__abstract" ]
                            [ text "The first lines of this post that gives the reader an idea what to expect from this post.                    " ]
                        , ul [ class "ui-article-preview__tags" ]
                            [ li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Some tag" ]
                                    ]
                                ]
                            , li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Another tag" ]
                                    ]
                                ]
                            ]
                        , div [ class "ui-article-preview__date" ]
                            [ text "Wednesday 2017-02-01" ]
                        , a [ class "ui-button", href "#" ]
                            [ span [ class "ui-button__label" ]
                                [ text "Read More...                        " ]
                            ]
                        ]
                    ]
                , li [ class "ui-article-list__item" ]
                    [ article [ class "ui-article-preview x-ui-article-preview--size-compact" ]
                        [ h4 [ class "ui-article-preview__title" ]
                            [ a [ href "#" ]
                                [ text "The oldest post" ]
                            ]
                        , ul [ class "ui-article-preview__tags" ]
                            [ li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Some tag" ]
                                    ]
                                ]
                            , li []
                                [ div [ class "ui-tag" ]
                                    [ a [ class "ui-tag__label", href "#" ]
                                        [ text "Another tag" ]
                                    ]
                                ]
                            ]
                        , a [ class "ui-button", href "#" ]
                            [ span [ class "ui-button__label" ]
                                [ text "Read More...                        " ]
                            ]
                        ]
                    ]
                ]
            ]
        , div [ class "ui-grid__col-4" ]
            [ section [ class "ui-tag-cloud" ]
                [ h3 []
                    [ text "Sidebar with Tags" ]
                , p []
                    [ text "Some info.            " ]
                , ul []
                    [ li []
                        [ div [ class "ui-tag" ]
                            [ a [ class "ui-tag__label", href "#" ]
                                [ text "Some tag" ]
                            ]
                        ]
                    , li []
                        [ div [ class "ui-tag" ]
                            [ a [ class "ui-tag__label", href "#" ]
                                [ text "Another tag" ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    , section []
        [ div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-12" ]
                [ h3 []
                    [ text "Grid" ]
                , p []
                    [ text "The default grid is using up to 12 flexbox columns.            " ]
                ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-1" ]
                [ text "Col-1        " ]
            , div [ class "ui-grid__col-11" ]
                [ text "Col-11        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-2" ]
                [ text "Col-2        " ]
            , div [ class "ui-grid__col-10" ]
                [ text "Col-10        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-3" ]
                [ text "Col-3        " ]
            , div [ class "ui-grid__col-9" ]
                [ text "Col-9        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-4" ]
                [ text "Col-4        " ]
            , div [ class "ui-grid__col-8" ]
                [ text "Col-8        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-5" ]
                [ text "Col-5        " ]
            , div [ class "ui-grid__col-7" ]
                [ text "Col-7        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-6" ]
                [ text "Col-6        " ]
            , div [ class "ui-grid__col-6" ]
                [ text "Col-6        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-7" ]
                [ text "Col-7        " ]
            , div [ class "ui-grid__col-5" ]
                [ text "Col-5        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-8" ]
                [ text "Col-8        " ]
            , div [ class "ui-grid__col-4" ]
                [ text "Col-4        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-9" ]
                [ text "Col-9        " ]
            , div [ class "ui-grid__col-3" ]
                [ text "Col-3        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-10" ]
                [ text "Col-10        " ]
            , div [ class "ui-grid__col-2" ]
                [ text "Col-2        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-11" ]
                [ text "Col-11        " ]
            , div [ class "ui-grid__col-1" ]
                [ text "Col-1        " ]
            ]
        , div [ class "ui-grid__row" ]
            [ div [ class "ui-grid__col-12" ]
                [ text "Fullsize (col-12)        " ]
            ]
        ]
    , div [ class "ui-grid__row" ]
        [ section [ class "ui-grid__col-6" ]
            [ h3 []
                [ text "Buttons" ]
            , p []
                [ text "Inline tex with            "
                , button [ class "ui-button" ]
                    [ span [ class "ui-button__label" ]
                        [ text "Real Button Button" ]
                    ]
                , button [ class "ui-button ui-button--primary" ]
                    [ span [ class "ui-button__label" ]
                        [ text "Primary Button" ]
                    ]
                , button [ class "ui-button ui-button--secondary" ]
                    [ span [ class "ui-button__label" ]
                        [ text "Secondary Button" ]
                    ]
                , a [ class "ui-button", href "#" ]
                    [ span [ class "ui-button__label" ]
                        [ text "Link Button" ]
                    ]
                , button [ class "ui-button ui-button--disabled", attribute "disabled" "disabled" ]
                    [ span [ class "ui-button__label" ]
                        [ text "Inactive Button" ]
                    ]
                ]
            ]
        , section [ class "ui-grid__col-6" ]
            [ form [ class "ui-form" ]
                [ h3 []
                    [ text "Forms" ]
                , label [ class "ui-form__group" ]
                    [ span [ class "ui-form__group-label" ]
                        [ text "Simple Textinput" ]
                    , input [ class "ui-form__text", name "simple-text", placeholder "Simple text...", type_ "text", value "" ]
                        []
                    , button [ class "ui-button", type_ "submit" ]
                        [ span [ class "ui-button__label" ]
                            [ text "OK" ]
                        ]
                    ]
                , label [ class "ui-form__group" ]
                    [ input [ class "ui-form__checkbox", name "check1", type_ "checkbox" ]
                        []
                    , span [ class "ui-form__group-label" ]
                        [ text "Simple Checkbox" ]
                    ]
                , label [ class "ui-form__group" ]
                    [ input [ class "ui-form__checkbox ui-form__checkbox--disabled", attribute "disabled" "disabled", name "check2", type_ "checkbox" ]
                        []
                    , span [ class "ui-form__group-label" ]
                        [ text "Simple Checkbox" ]
                    ]
                , label [ class "ui-form__group" ]
                    [ input [ class "ui-form__radio", name "radio1", type_ "radio", value "value1" ]
                        []
                    , span [ class "ui-form__group-label" ]
                        [ text "Option 1" ]
                    ]
                , label [ class "ui-form__group" ]
                    [ input [ class "ui-form__radio", name "radio1", type_ "radio", value "value2" ]
                        []
                    , span [ class "ui-form__group-label" ]
                        [ text "Option 2" ]
                    ]
                , label [ class "ui-form__group" ]
                    [ input [ class "ui-form__radio ui-form__radio--disabled", attribute "disabled" "disabled", name "radio1", type_ "radio", value "value3" ]
                        []
                    , span [ class "ui-form__group-label" ]
                        [ text "Option 2" ]
                    ]
                , label [ class "ui-form__group" ]
                    [ span [ class "ui-form__group-label" ]
                        [ text "Some text" ]
                    , textarea [ class "ui-form__textarea", name "textarea", value "value2" ]
                        []
                    ]
                , label [ class "ui-form__group" ]
                    [ span [ class "ui-form__group-label" ]
                        [ text "Some text" ]
                    , select [ class "ui-form__select", name "select1" ]
                        [ option [ value "1" ]
                            [ text "1" ]
                        , optgroup [ attribute "label" "Section 2" ]
                            [ option [ value "2.1" ]
                                [ text "2.1" ]
                            , option [ value "2.2" ]
                                [ text "2.2" ]
                            ]
                        , optgroup [ attribute "label" "Section 3" ]
                            [ option [ value "3.1" ]
                                [ text "3.1" ]
                            , option [ value "3.2" ]
                                [ text "3.2" ]
                            , option [ value "3.3" ]
                                [ text "3.3" ]
                            ]
                        ]
                    ]
                , button [ class "ui-button", type_ "submit" ]
                    [ span [ class "ui-button__label" ]
                        [ text "Submit" ]
                    ]
                ]
            ]
        ]
    ]
